HOME_KPIS_QUERY = """
SELECT
    (
        SELECT p.PHOSPHATE_PRICE_USD
        FROM GOLD.FACT_PRICE AS p
        INNER JOIN GOLD.DIM_DATE AS d
            ON p.DATE_KEY = d.DATE_KEY
        ORDER BY d.FULL_DATE DESC
        LIMIT 1
    ) AS LATEST_PRICE,

    (
        SELECT COUNT(*)
        FROM GOLD.DIM_COUNTRY
    ) AS COUNTRIES_COUNT,

    (
        SELECT MAX(YEAR)
        FROM GOLD.FACT_PRICE_FORECAST
    ) AS FORECAST_END_YEAR,

    (
        SELECT COUNT(*)
        FROM GOLD.FACT_PRICE_FORECAST
    ) AS FORECAST_ROWS
"""


HISTORICAL_PRICE_QUERY = """
SELECT
    d.FULL_DATE AS DATE,
    p.PHOSPHATE_PRICE_USD
FROM GOLD.FACT_PRICE AS p
INNER JOIN GOLD.DIM_DATE AS d
    ON p.DATE_KEY = d.DATE_KEY
ORDER BY d.FULL_DATE
"""


FORECAST_QUERY = """
SELECT
    DATE,
    FORECAST_PRICE_USD,
    MODEL_NAME
FROM GOLD.FACT_PRICE_FORECAST
ORDER BY DATE
"""